/*
 * File: app/store/UserRoleStore.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('webapp.store.UserRoleStore', {
    extend: 'Ext.data.Store',

    requires: [
        'webapp.model.UserRoleModel',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'webapp.model.UserRoleModel',
            storeId: 'UserRoleStore',
            proxy: {
                type: 'ajax',
                url: 'user/rolelist',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});