/*
 * File: app/model/UserModel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('webapp.model.UserModel', {
    extend: 'Ext.data.Model',
    alias: 'model.UserModel',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'password',
            type: 'string'
        },
        {
            name: 'fullName'
        },
        {
            name: 'userRoleName',
            type: 'auto'
        },
        {
            name: 'email'
        },
        {
            name: 'createdDateString'
        },
        {
            name: 'lastLoginDateString'
        },
        {
            name: 'id',
            type: 'int'
        },
        {
            name: 'username',
            type: 'string'
        }
    ]
});