/*
 * File: app/controller/DatasourceController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('webapp.controller.DatasourceController', {
    extend: 'Ext.app.Controller',

    onClickLinkNewDatasource: function(button, e, eOpts) {
        this.showLinkDatasourceWindow(GlobalData.lastSelectedMenuId, "new");
    },

    onMybutton38Click: function(button, e, eOpts) {
        var selectedDsIds = "";
        var items = Ext.getCmp("allDatasourceGrid").getStore();
        items.each(function(rec){
            if(rec.get("selected") === true){
                selectedDsIds += "#" + rec.get("id");
            }
        });

        var restartTomcat = Ext.getCmp("restartTomcatCheckbox").getValue();
        var window = Ext.getCmp("linkNewDataSourceWindow");
        var url = GlobalData.urlPrefix + "datasource/tomcat/link/save";
        Ext.Ajax.request({
            url: url,
            params: {"ids":selectedDsIds, "tomcatId" : GlobalData.lastSelectedMenuId,"isRestart":restartTomcat},
            success: function(resp, ops) {
                var response = Ext.decode(resp.responseText);
                if(response.success === true){
                    Ext.getCmp("tomcatDatasourcesGrid").getStore().loadData(response.data);
                    window.close();
                }
                else {
                    Ext.Msg.show({
                        title: "Message",
                        msg: response.msg,
                        buttons: Ext.Msg.OK,
                        icon: Ext.Msg.WARNING
                    });
                }
            },

        });
    },

    showLinkDatasourceWindow: function(tomcatId, type) {
        var window = Ext.create("widget.LinkNewDataSourceWindow");
        var url = GlobalData.urlPrefix + "datasource/tomcat/link/list";
        Ext.Ajax.request({
            url: url,
            params: {"tomcatId" : GlobalData.lastSelectedMenuId},
            success: function(resp, ops) {
                var response = Ext.decode(resp.responseText);
                if(response.success === true){
                    var gridStore = Ext.getCmp("allDatasourceGrid").getStore();
                    gridStore.loadData(response.data);
                    //load name, state of tomcat
                    Ext.getCmp("linkDatasourceTomcatNameField").setValue(Ext.getCmp("tomcatNameField").getValue());
                    Ext.getCmp("linkDatasourceTomcatStatusField").setValue(Ext.getCmp("tomcatStateField").getValue());

                }
                else {
                    Ext.Msg.show({
                        title: "Message",
                        msg: response.msg,
                        buttons: Ext.Msg.OK,
                        icon: Ext.Msg.WARNING
                    });
                }
            }
        });
        window.show();
    },

    getDatasourceListByTomcat: function(tomcatId, callback) {
        var url = GlobalData.urlPrefix + "tomcat/instance/datasource";
        Ext.Ajax.request({
            url: url,
            params: {"tomcatId" : tomcatId},
            success: function(resp, ops) {
                var response = Ext.decode(resp.responseText);
                if(response.success === true){
                    callback(response.data);
                }
                else {
                    Ext.Msg.show({
                        title: "Message",
                        msg: response.msg,
                        buttons: Ext.Msg.OK,
                        icon: Ext.Msg.WARNING
                    });
                }
            }
        });
    },

    removeDs: function(tomcatId, dsId) {
           Ext.MessageBox.confirm('Confirm', 'Are you sure you want to remove this datasource?', function(btn){

               if(btn == "yes"){
                   var url = GlobalData.urlPrefix + "datasource/tomcat/link/remove";
                   Ext.Ajax.request({
                       url: url,
                       params: {"tomcatId" : tomcatId, "dsId":dsId},
                       success: function(resp, ops) {
                           var response = Ext.decode(resp.responseText);
                           if(response.success === true){
                               Ext.getCmp("tomcatDatasourcesGrid").getStore().loadData(response.data);
                           }
                           else {
                               Ext.Msg.show({
                                   title: "Message",
                                   msg: response.msg,
                                   buttons: Ext.Msg.OK,
                                   icon: Ext.Msg.WARNING
                               });
                           }
                       }
                   });
               }});
    },

    init: function(application) {
        this.control({
            "#btnLinkNewDatasource": {
                click: this.onClickLinkNewDatasource
            },
            "#mybutton38": {
                click: this.onMybutton38Click
            }
        });
    }

});
