/*
 * File: app/controller/DatagridServerController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('webapp.controller.DatagridServerController', {
    extend: 'Ext.app.Controller',

    onDatagridServerGroupGridSelect: function(rowmodel, record, index, eOpts) {
        var id = record.get("id");
        var url = GlobalData.urlPrefix + "res/datagrid/list";
        Ext.Ajax.request({
            url: url,
            params: {"groupId": id},
            success: function(resp, ops) {
                var response = Ext.decode(resp.responseText);
                if (response.success === true){
                    Ext.getCmp("datagirdServerGrid").getStore().loadData(response.data);
                }
                else {
                    Ext.Msg.show({
                        title: "Message",
                        msg: response.msg,
                        buttons: Ext.Msg.OK,
                        icon: Ext.Msg.WARNING
                    });
                }
            },
            method: "GET"
        });
    },

    init: function(application) {
        this.control({
            "#datagridServerGroupGrid": {
                select: this.onDatagridServerGroupGridSelect
            }
        });
    }

});
