/*
 * File: app/controller/TomcatInstWizardController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('webapp.controller.TomcatInstWizardController', {
    extend: 'Ext.app.Controller',

    onStep2Activate: function(component, eOpts) {
        Ext.getCmp('next-btn').setText('Save & Next &raquo;');
        component.down('gridpanel').getStore().load();
    },

    onStep3Activate: function(component, eOpts) {
        Ext.getCmp('next-btn').setText('Install');
        component.down('gridpanel').getStore().load();
    },

    onDSCreateButtonClick: function(button, e, eOpts) {
                Ext.create('widget.dsWin').show();
    },

    onNextButtonClick: function(button, e, eOpts) {

        var layout = button.up("panel").getLayout();//must be CardLayout

        if (layout.getNext()) {
            layout.next();
        }

    },

    onPrevButtonClick: function(button, e, eOpts) {

        var layout = button.up("panel").getLayout();
        layout.prev();
        button.setDisabled(!layout.getPrev());
    },

    init: function(application) {
        this.control({
            "ticWizard #step2": {
                activate: this.onStep2Activate
            },
            "ticWizard #step3": {
                activate: this.onStep3Activate
            },
            "ticWizard #btnWCreateDs": {
                click: this.onDSCreateButtonClick
            },
            "ticWizard #next-btn": {
                click: this.onNextButtonClick
            },
            "ticWizard #prev-btn": {
                click: this.onPrevButtonClick
            }
        });
    }

});
