/*
 * File: app/view/ClusteringConfigurationWindow.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('webapp.view.ClusteringConfigurationWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.ClusteringConfigurationWindow',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.button.Button',
        'Ext.form.field.Hidden'
    ],

    height: 159,
    width: 400,
    title: 'New Configuration ',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    id: 'ClusteringConfigurationForm',
                    bodyPadding: 10,
                    title: '',
                    items: [
                        {
                            xtype: 'textfield',
                            id: 'configNameTextField',
                            margin: '10 0 10 10',
                            width: 352,
                            fieldLabel: 'Name'
                        },
                        {
                            xtype: 'textfield',
                            id: 'configValueTextField',
                            margin: '0 0 10 10',
                            width: 353,
                            fieldLabel: 'Value'
                        },
                        {
                            xtype: 'button',
                            id: 'btnSubmitClusteringConfig',
                            margin: '0 0 0 120',
                            text: 'Create'
                        },
                        {
                            xtype: 'button',
                            margin: '0 0 0 10',
                            text: 'Cancel'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            id: 'IDHiddenField',
                            fieldLabel: 'Label'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});