/*
 * File: app/view/dashboardPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('webapp.view.dashboardPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.dashboardpanel',

    requires: [
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Line'
    ],

    height: 792,
    itemId: 'dashboardPanel',
    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'container',
                    flex: 4,
                    dock: 'top',
                    layout: {
                        align: 'stretch',
                        type: 'hbox'
                    }
                },
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'combobox',
                            fieldLabel: 'Domain',
                            store: 'DomainStore'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    dock: 'top',
                    animCollapse: false,
                    collapseDirection: 'top',
                    collapsible: true,
                    placeholderCollapseHideMode: 2,
                    title: 'Tomcat 1',
                    titleCollapse: true,
                    dockedItems: [
                        {
                            xtype: 'container',
                            dock: 'top',
                            height: 66,
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    height: 70,
                                    width: 171,
                                    layout: {
                                        align: 'stretch',
                                        pack: 'center',
                                        type: 'vbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'label',
                                            margins: '1',
                                            height: 21,
                                            html: '<center><span style="font-weight: bold;text-align:center;font-size:large;color:blue">Health</span></center>',
                                            width: 37,
                                            text: ''
                                        },
                                        {
                                            xtype: 'label',
                                            height: 21,
                                            style: 'font-size:medium;font-weight:bold; text-align:center;',
                                            width: 171,
                                            text: '100%'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    height: 70,
                                    width: 171,
                                    layout: {
                                        align: 'stretch',
                                        pack: 'center',
                                        type: 'vbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'label',
                                            margins: '1',
                                            height: 21,
                                            html: '<center><span style="font-weight: bold;text-align:center;font-size:large;color:blue">Today Availability</span></center>',
                                            width: 37,
                                            text: ''
                                        },
                                        {
                                            xtype: 'label',
                                            height: 21,
                                            margin: '0 0 0 30',
                                            style: 'font-size:medium;font-weight:bold; text-align:center;',
                                            width: 171,
                                            text: '100%'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    height: 70,
                                    width: 171,
                                    layout: {
                                        align: 'stretch',
                                        pack: 'center',
                                        type: 'vbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'label',
                                            margins: '1',
                                            height: 21,
                                            html: '<center><span style="font-weight: bold;text-align:center;font-size:large;color:blue">Today\'s Uptime</span></center>',
                                            width: 37,
                                            text: ''
                                        },
                                        {
                                            xtype: 'label',
                                            height: 21,
                                            style: 'font-size:medium;font-weight:bold; text-align:center;',
                                            width: 37,
                                            text: '11 hrs 11 mins 26 secs'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    height: 70,
                                    width: 171,
                                    layout: {
                                        align: 'stretch',
                                        pack: 'center',
                                        type: 'vbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'label',
                                            margins: '1',
                                            height: 21,
                                            html: '<center><span style="font-weight: bold;text-align:center;font-size:large;color:blue">Last Downtime</span></center>',
                                            width: 37,
                                            text: ''
                                        },
                                        {
                                            xtype: 'label',
                                            height: 21,
                                            style: 'font-size:medium;font-weight:bold; text-align:center;',
                                            width: 37,
                                            text: '1 hrs 51 mins 26 secs'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            dock: 'bottom',
                            height: 233,
                            width: 657,
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'panel',
                                    width: 600,
                                    layout: {
                                        type: 'fit'
                                    },
                                    title: 'Server Response Time',
                                    titleAlign: 'center',
                                    dockedItems: [
                                        {
                                            xtype: 'chart',
                                            dock: 'top',
                                            height: 184,
                                            html: 'SERVER RESPONE TIME',
                                            width: 598,
                                            animate: true,
                                            insetPadding: 20,
                                            store: 'DomainStore',
                                            axes: [
                                                {
                                                    type: 'Category',
                                                    fields: [
                                                        'x'
                                                    ],
                                                    title: 'Response Time',
                                                    position: 'bottom'
                                                },
                                                {
                                                    type: 'Numeric',
                                                    fields: [
                                                        'y'
                                                    ],
                                                    title: 'ms',
                                                    position: 'left'
                                                }
                                            ],
                                            series: [
                                                {
                                                    type: 'line',
                                                    xField: 'x',
                                                    yField: 'y',
                                                    smooth: 3
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    width: 634,
                                    title: 'Server Performance',
                                    titleAlign: 'center',
                                    dockedItems: [
                                        {
                                            xtype: 'chart',
                                            dock: 'top',
                                            height: 184,
                                            width: 598,
                                            animate: true,
                                            insetPadding: 20,
                                            store: 'DomainStore',
                                            axes: [
                                                {
                                                    type: 'Category',
                                                    fields: [
                                                        'x'
                                                    ],
                                                    title: 'Time',
                                                    position: 'bottom'
                                                },
                                                {
                                                    type: 'Numeric',
                                                    fields: [
                                                        'y'
                                                    ],
                                                    title: 'ms',
                                                    position: 'left'
                                                }
                                            ],
                                            series: [
                                                {
                                                    type: 'line',
                                                    xField: 'x',
                                                    yField: 'y',
                                                    smooth: 3
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    dock: 'top',
                    collapseDirection: 'top',
                    collapsed: false,
                    collapsible: true,
                    title: 'Tomcat 2',
                    dockedItems: [
                        {
                            xtype: 'container',
                            dock: 'top',
                            height: 66,
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    height: 70,
                                    width: 171,
                                    layout: {
                                        align: 'stretch',
                                        pack: 'center',
                                        type: 'vbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'label',
                                            margins: '1',
                                            height: 21,
                                            html: '<center><span style="font-weight: bold;text-align:center;font-size:large;color:blue">Health</span></center>',
                                            width: 37,
                                            text: ''
                                        },
                                        {
                                            xtype: 'label',
                                            height: 21,
                                            style: 'font-size:medium;font-weight:bold; text-align:center;',
                                            width: 171,
                                            text: '100%'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    height: 70,
                                    width: 171,
                                    layout: {
                                        align: 'stretch',
                                        pack: 'center',
                                        type: 'vbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'label',
                                            margins: '1',
                                            height: 21,
                                            html: '<center><span style="font-weight: bold;text-align:center;font-size:large;color:blue">Today Availability</span></center>',
                                            width: 37,
                                            text: ''
                                        },
                                        {
                                            xtype: 'label',
                                            height: 21,
                                            margin: '0 0 0 30',
                                            style: 'font-size:medium;font-weight:bold; text-align:center;',
                                            width: 171,
                                            text: '100%'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    height: 70,
                                    width: 171,
                                    layout: {
                                        align: 'stretch',
                                        pack: 'center',
                                        type: 'vbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'label',
                                            margins: '1',
                                            height: 21,
                                            html: '<center><span style="font-weight: bold;text-align:center;font-size:large;color:blue">Today\'s Uptime</span></center>',
                                            width: 37,
                                            text: ''
                                        },
                                        {
                                            xtype: 'label',
                                            height: 21,
                                            style: 'font-size:medium;font-weight:bold; text-align:center;',
                                            width: 37,
                                            text: '11 hrs 11 mins 26 secs'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    height: 70,
                                    width: 171,
                                    layout: {
                                        align: 'stretch',
                                        pack: 'center',
                                        type: 'vbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'label',
                                            margins: '1',
                                            height: 21,
                                            html: '<center><span style="font-weight: bold;text-align:center;font-size:large;color:blue">Last Downtime</span></center>',
                                            width: 37,
                                            text: ''
                                        },
                                        {
                                            xtype: 'label',
                                            height: 21,
                                            style: 'font-size:medium;font-weight:bold; text-align:center;',
                                            width: 37,
                                            text: '1 hrs 51 mins 26 secs'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            dock: 'bottom',
                            height: 233,
                            width: 657,
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'panel',
                                    width: 600,
                                    layout: {
                                        type: 'fit'
                                    },
                                    title: 'Server Response Time',
                                    titleAlign: 'center',
                                    dockedItems: [
                                        {
                                            xtype: 'chart',
                                            dock: 'top',
                                            height: 184,
                                            html: 'SERVER RESPONE TIME',
                                            width: 598,
                                            animate: true,
                                            insetPadding: 20,
                                            store: 'DomainStore',
                                            axes: [
                                                {
                                                    type: 'Category',
                                                    fields: [
                                                        'x'
                                                    ],
                                                    title: 'Response Time',
                                                    position: 'bottom'
                                                },
                                                {
                                                    type: 'Numeric',
                                                    fields: [
                                                        'y'
                                                    ],
                                                    title: 'ms',
                                                    position: 'left'
                                                }
                                            ],
                                            series: [
                                                {
                                                    type: 'line',
                                                    xField: 'x',
                                                    yField: 'y',
                                                    smooth: 3
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    width: 634,
                                    title: 'Server Performance',
                                    titleAlign: 'center',
                                    dockedItems: [
                                        {
                                            xtype: 'chart',
                                            dock: 'top',
                                            height: 184,
                                            width: 598,
                                            animate: true,
                                            insetPadding: 20,
                                            store: 'DomainStore',
                                            axes: [
                                                {
                                                    type: 'Category',
                                                    fields: [
                                                        'x'
                                                    ],
                                                    title: 'Time',
                                                    position: 'bottom'
                                                },
                                                {
                                                    type: 'Numeric',
                                                    fields: [
                                                        'y'
                                                    ],
                                                    title: 'ms',
                                                    position: 'left'
                                                }
                                            ],
                                            series: [
                                                {
                                                    type: 'line',
                                                    xField: 'x',
                                                    yField: 'y',
                                                    smooth: 3
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});