/*
 * File: app/view/DataSourceServerWindow.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('webapp.view.DataSourceServerWindow', {
    extend: 'Ext.window.Window',

    height: 273,
    width: 517,
    title: 'Target Server',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    margin: '10 10 10 10',
                    layout: {
                        align: 'stretch',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'gridpanel',
                            flex: 4,
                            title: 'Available Servers',
                            titleAlign: 'center',
                            forceFit: true,
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    align: 'center',
                                    dataIndex: 'string',
                                    text: 'Name'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    align: 'center',
                                    dataIndex: 'string',
                                    text: 'IP Address'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            width: 100,
                            items: [
                                {
                                    xtype: 'button',
                                    margin: '30 0 10 10',
                                    text: '&nbsp;>&nbsp;'
                                },
                                {
                                    xtype: 'button',
                                    margin: '0 0 10 10',
                                    text: '>>'
                                },
                                {
                                    xtype: 'button',
                                    margin: '0 0 10 10',
                                    text: '&nbsp;<&nbsp;'
                                },
                                {
                                    xtype: 'button',
                                    margin: '0 0 0 10',
                                    text: '<<'
                                }
                            ]
                        },
                        {
                            xtype: 'gridpanel',
                            flex: 4,
                            title: 'Selected Servers',
                            titleAlign: 'center',
                            forceFit: true,
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    align: 'center',
                                    dataIndex: 'string',
                                    text: 'Name'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    align: 'center',
                                    dataIndex: 'string',
                                    text: 'IP Address'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'button',
                    margin: '0 0 0 200',
                    text: 'Save'
                },
                {
                    xtype: 'button',
                    margin: '0 0 0 10',
                    text: 'Cancel'
                }
            ]
        });

        me.callParent(arguments);
    }

});