/*
 * File: app/view/DetailMonitoringTomcatInstance.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('webapp.view.DetailMonitoringTomcatInstance', {
    extend: 'Ext.container.Container',
    alias: 'widget.detailmonitoringtomcatinstance',

    requires: [
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.field.Display',
        'Ext.chart.Chart',
        'Ext.util.Point',
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Line',
        'Ext.chart.series.Column',
        'Ext.chart.Legend',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.column.Boolean',
        'Ext.grid.View'
    ],

    autoScroll: true,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    flex: 10,
                    id: 'detailTomcatMonitoringTab',
                    itemId: 'tabPanel',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            autoScroll: true,
                            manageHeight: false,
                            title: 'Overview',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            dockedItems: [
                                {
                                    xtype: 'panel',
                                    dock: 'top',
                                    manageHeight: false,
                                    items: [
                                        {
                                            xtype: 'displayfield',
                                            fieldLabel: 'Health',
                                            value: 'OK'
                                        },
                                        {
                                            xtype: 'displayfield',
                                            fieldLabel: 'Availability',
                                            value: 'OK'
                                        },
                                        {
                                            xtype: 'displayfield',
                                            width: 212,
                                            fieldLabel: 'Today\'s Availability',
                                            value: '100%'
                                        },
                                        {
                                            xtype: 'displayfield',
                                            width: 238,
                                            fieldLabel: 'Today\'s Uptime',
                                            value: '12 hrs 10 mins 13 secs'
                                        },
                                        {
                                            xtype: 'displayfield',
                                            width: 265,
                                            fieldLabel: 'Last Downtime',
                                            value: 'N/A'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    dock: 'top',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            margin: '5 5 5 5',
                                            layout: 'fit',
                                            title: 'Availability history for last 6 hours',
                                            titleAlign: 'center',
                                            dockedItems: [
                                                {
                                                    xtype: 'chart',
                                                    dock: 'top',
                                                    height: 250,
                                                    width: 400,
                                                    animate: true,
                                                    insetPadding: 20,
                                                    store: 'TempoStore',
                                                    axes: [
                                                        {
                                                            type: 'Category',
                                                            fields: [
                                                                'x'
                                                            ],
                                                            position: 'left',
                                                            title: 'Category Axis'
                                                        },
                                                        {
                                                            type: 'Numeric',
                                                            fields: [
                                                                'y'
                                                            ],
                                                            position: 'bottom',
                                                            title: 'Numeric Axis'
                                                        }
                                                    ],
                                                    series: [
                                                        {
                                                            type: 'bar',
                                                            label: {
                                                                display: 'insideEnd',
                                                                field: 'y',
                                                                color: '#333',
                                                                'text-anchor': 'middle'
                                                            },
                                                            axis: 'bottom',
                                                            xField: 'x',
                                                            yField: 'y'
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            margin: '5 5 5 5',
                                            layout: 'fit',
                                            title: 'Performance history for last 6 hours',
                                            titleAlign: 'center',
                                            dockedItems: [
                                                {
                                                    xtype: 'chart',
                                                    dock: 'top',
                                                    height: 250,
                                                    width: 400,
                                                    animate: true,
                                                    insetPadding: 20,
                                                    store: 'TempoStore',
                                                    axes: [
                                                        {
                                                            type: 'Category',
                                                            fields: [
                                                                'x'
                                                            ],
                                                            position: 'left',
                                                            title: 'Category Axis'
                                                        },
                                                        {
                                                            type: 'Numeric',
                                                            fields: [
                                                                'y'
                                                            ],
                                                            position: 'bottom',
                                                            title: 'Numeric Axis'
                                                        }
                                                    ],
                                                    series: [
                                                        {
                                                            type: 'bar',
                                                            label: {
                                                                display: 'insideEnd',
                                                                field: 'y',
                                                                color: '#333',
                                                                'text-anchor': 'middle'
                                                            },
                                                            axis: 'bottom',
                                                            xField: 'x',
                                                            yField: 'y'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    dock: 'top',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            margin: '5 5 5 5',
                                            layout: 'fit',
                                            title: 'Server response time',
                                            titleAlign: 'center',
                                            dockedItems: [
                                                {
                                                    xtype: 'chart',
                                                    dock: 'top',
                                                    height: 250,
                                                    width: 400,
                                                    animate: true,
                                                    insetPadding: 20,
                                                    store: 'TempoStore',
                                                    axes: [
                                                        {
                                                            type: 'Category',
                                                            fields: [
                                                                'x'
                                                            ],
                                                            title: 'Category Axis',
                                                            position: 'bottom'
                                                        },
                                                        {
                                                            type: 'Numeric',
                                                            fields: [
                                                                'y'
                                                            ],
                                                            title: 'Numeric Axis',
                                                            position: 'left'
                                                        }
                                                    ],
                                                    series: [
                                                        {
                                                            type: 'line',
                                                            xField: 'x',
                                                            yField: 'y',
                                                            smooth: 3
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            margin: '5 5 5 5',
                                            layout: 'fit',
                                            title: 'Server performance',
                                            titleAlign: 'center',
                                            dockedItems: [
                                                {
                                                    xtype: 'chart',
                                                    dock: 'top',
                                                    height: 250,
                                                    width: 400,
                                                    animate: true,
                                                    insetPadding: 20,
                                                    store: 'TempoStore',
                                                    axes: [
                                                        {
                                                            type: 'Category',
                                                            fields: [
                                                                'x'
                                                            ],
                                                            title: 'Category Axis',
                                                            position: 'bottom'
                                                        },
                                                        {
                                                            type: 'Numeric',
                                                            fields: [
                                                                'y'
                                                            ],
                                                            title: 'Numeric Axis',
                                                            position: 'left'
                                                        }
                                                    ],
                                                    series: [
                                                        {
                                                            type: 'line',
                                                            xField: 'x',
                                                            yField: 'y',
                                                            smooth: 3
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    dock: 'top',
                                    autoScroll: true,
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            margin: '5 5 5 5',
                                            layout: 'fit',
                                            manageHeight: false,
                                            title: 'Thread Usage',
                                            titleAlign: 'center',
                                            dockedItems: [
                                                {
                                                    xtype: 'chart',
                                                    dock: 'top',
                                                    height: 250,
                                                    width: 400,
                                                    animate: true,
                                                    insetPadding: 20,
                                                    store: 'TempoStore',
                                                    axes: [
                                                        {
                                                            type: 'Category',
                                                            fields: [
                                                                'x'
                                                            ],
                                                            title: 'Category Axis',
                                                            position: 'bottom'
                                                        },
                                                        {
                                                            type: 'Numeric',
                                                            fields: [
                                                                'y'
                                                            ],
                                                            title: 'Numeric Axis',
                                                            position: 'left'
                                                        }
                                                    ],
                                                    series: [
                                                        {
                                                            type: 'line',
                                                            xField: 'x',
                                                            yField: 'y',
                                                            smooth: 3
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            margin: '5 5 5 5',
                                            layout: 'fit',
                                            manageHeight: false,
                                            title: 'Class Loading',
                                            titleAlign: 'center',
                                            dockedItems: [
                                                {
                                                    xtype: 'chart',
                                                    dock: 'top',
                                                    height: 250,
                                                    width: 400,
                                                    animate: true,
                                                    insetPadding: 20,
                                                    store: 'TempoStore',
                                                    axes: [
                                                        {
                                                            type: 'Category',
                                                            fields: [
                                                                'x'
                                                            ],
                                                            title: 'Category Axis',
                                                            position: 'bottom'
                                                        },
                                                        {
                                                            type: 'Numeric',
                                                            fields: [
                                                                'y'
                                                            ],
                                                            title: 'Numeric Axis',
                                                            position: 'left'
                                                        }
                                                    ],
                                                    series: [
                                                        {
                                                            type: 'line',
                                                            xField: 'x',
                                                            yField: 'y',
                                                            smooth: 3
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    dock: 'top',
                                    autoScroll: true,
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            layout: 'fit',
                                            title: 'Response summary'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'chart',
                                    flex: 1,
                                    dock: 'top',
                                    height: 250,
                                    width: 400,
                                    animate: true,
                                    insetPadding: 20,
                                    store: 'TempoStore',
                                    axes: [
                                        {
                                            type: 'Category',
                                            fields: [
                                                'x'
                                            ],
                                            title: 'Category Axis',
                                            position: 'bottom'
                                        },
                                        {
                                            type: 'Numeric',
                                            fields: [
                                                'y'
                                            ],
                                            title: 'Numeric Axis',
                                            position: 'left'
                                        }
                                    ],
                                    series: [
                                        {
                                            type: 'line',
                                            xField: 'x',
                                            yField: 'y',
                                            smooth: 3
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            autoScroll: true,
                            title: 'Memory',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            dockedItems: [
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    dock: 'top',
                                    autoScroll: true,
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            margin: '5 5 5 5',
                                            layout: 'fit',
                                            title: 'Memory Utilization',
                                            titleAlign: 'center',
                                            dockedItems: [
                                                {
                                                    xtype: 'chart',
                                                    dock: 'top',
                                                    height: 250,
                                                    width: 400,
                                                    animate: true,
                                                    insetPadding: 20,
                                                    store: 'TempoStore',
                                                    axes: [
                                                        {
                                                            type: 'Category',
                                                            fields: [
                                                                'x'
                                                            ],
                                                            title: 'Category Axis',
                                                            position: 'bottom'
                                                        },
                                                        {
                                                            type: 'Numeric',
                                                            fields: [
                                                                'y'
                                                            ],
                                                            title: 'Numeric Axis',
                                                            position: 'left'
                                                        }
                                                    ],
                                                    series: [
                                                        {
                                                            type: 'column',
                                                            label: {
                                                                display: 'insideEnd',
                                                                field: 'y',
                                                                color: '#333',
                                                                'text-anchor': 'middle'
                                                            },
                                                            xField: 'x',
                                                            yField: 'y'
                                                        }
                                                    ],
                                                    legend: {

                                                    }
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            margin: '5 5 5 5',
                                            layout: 'fit',
                                            title: 'Memory Usage',
                                            titleAlign: 'center',
                                            dockedItems: [
                                                {
                                                    xtype: 'chart',
                                                    dock: 'top',
                                                    height: 250,
                                                    width: 400,
                                                    animate: true,
                                                    insetPadding: 20,
                                                    store: 'TempoStore',
                                                    axes: [
                                                        {
                                                            type: 'Category',
                                                            fields: [
                                                                'x'
                                                            ],
                                                            title: 'Category Axis',
                                                            position: 'bottom'
                                                        },
                                                        {
                                                            type: 'Numeric',
                                                            fields: [
                                                                'y'
                                                            ],
                                                            title: 'Numeric Axis',
                                                            position: 'left'
                                                        }
                                                    ],
                                                    series: [
                                                        {
                                                            type: 'line',
                                                            xField: 'x',
                                                            yField: 'y',
                                                            smooth: 3
                                                        }
                                                    ],
                                                    legend: {

                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 4,
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            margin: '5 5 5 5',
                                            collapsible: true,
                                            title: 'Memory Usage',
                                            forceFit: true,
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'Name'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'number',
                                                    text: 'Type'
                                                },
                                                {
                                                    xtype: 'datecolumn',
                                                    dataIndex: 'date',
                                                    text: 'Used Memory(MB)'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Committed Memory(MB)'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Maxium Memory(MB)'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Used Memory (%)'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Free Memory (%)'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Health'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ],
                            items: [
                                {
                                    xtype: 'panel',
                                    flex: 4,
                                    margin: '5 5 5 5',
                                    layout: 'fit',
                                    collapsible: true,
                                    title: 'Garbage Collector',
                                    dockedItems: [
                                        {
                                            xtype: 'chart',
                                            dock: 'top',
                                            height: 150,
                                            width: 400,
                                            animate: true,
                                            insetPadding: 20,
                                            store: 'TempoStore',
                                            axes: [
                                                {
                                                    type: 'Category',
                                                    fields: [
                                                        'x'
                                                    ],
                                                    title: 'Category Axis',
                                                    position: 'bottom'
                                                },
                                                {
                                                    type: 'Numeric',
                                                    fields: [
                                                        'y'
                                                    ],
                                                    title: 'Numeric Axis',
                                                    position: 'left'
                                                }
                                            ],
                                            series: [
                                                {
                                                    type: 'line',
                                                    xField: 'x',
                                                    yField: 'y',
                                                    smooth: 3
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            autoScroll: true,
                            title: 'Thread',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            dockedItems: [
                                {
                                    xtype: 'container',
                                    flex: 4,
                                    dock: 'top',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            margin: '5 5 5 5',
                                            layout: 'fit',
                                            title: 'Thread Pool Utilization',
                                            titleAlign: 'center',
                                            dockedItems: [
                                                {
                                                    xtype: 'chart',
                                                    dock: 'top',
                                                    height: 250,
                                                    width: 400,
                                                    animate: true,
                                                    insetPadding: 20,
                                                    store: 'TempoStore',
                                                    axes: [
                                                        {
                                                            type: 'Category',
                                                            fields: [
                                                                'x'
                                                            ],
                                                            title: 'Category Axis',
                                                            position: 'bottom'
                                                        },
                                                        {
                                                            type: 'Numeric',
                                                            fields: [
                                                                'y'
                                                            ],
                                                            title: 'Numeric Axis',
                                                            position: 'left'
                                                        }
                                                    ],
                                                    series: [
                                                        {
                                                            type: 'column',
                                                            label: {
                                                                display: 'insideEnd',
                                                                field: 'y',
                                                                color: '#333',
                                                                'text-anchor': 'middle'
                                                            },
                                                            xField: 'x',
                                                            yField: 'y'
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            margin: '5 5 5 5',
                                            layout: 'fit',
                                            title: 'Busy Threads',
                                            titleAlign: 'center',
                                            dockedItems: [
                                                {
                                                    xtype: 'chart',
                                                    dock: 'top',
                                                    height: 250,
                                                    id: 'tomcatBusyThreadChart',
                                                    width: 400,
                                                    animate: true,
                                                    insetPadding: 20,
                                                    store: 'TomcatBusyThreadStore',
                                                    axes: [
                                                        {
                                                            type: 'Category',
                                                            fields: [
                                                                'time'
                                                            ],
                                                            title: 'Timestamp',
                                                            position: 'bottom'
                                                        },
                                                        {
                                                            type: 'Numeric',
                                                            fields: [
                                                                'value'
                                                            ],
                                                            title: 'Value',
                                                            position: 'left'
                                                        }
                                                    ],
                                                    series: [
                                                        {
                                                            type: 'line',
                                                            title: 'Busy threads',
                                                            xField: 'time',
                                                            yField: 'value',
                                                            smooth: 3
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ],
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 4,
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            margin: '5 5 5 5',
                                            collapsible: true,
                                            title: 'Thread pool details',
                                            forceFit: true,
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'Connector Name'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'number',
                                                    text: 'Busy Threads'
                                                },
                                                {
                                                    xtype: 'datecolumn',
                                                    dataIndex: 'date',
                                                    text: 'Maxium Threads'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Percentage Used'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Percentage Free'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Health'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            autoScroll: true,
                            title: 'JDBC',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'panel',
                                    flex: 1,
                                    layout: 'fit',
                                    title: 'Active Connections',
                                    dockedItems: [
                                        {
                                            xtype: 'chart',
                                            dock: 'top',
                                            height: 250,
                                            width: 400,
                                            animate: true,
                                            insetPadding: 20,
                                            store: 'TempoStore',
                                            axes: [
                                                {
                                                    type: 'Category',
                                                    fields: [
                                                        'x'
                                                    ],
                                                    title: 'Category Axis',
                                                    position: 'bottom'
                                                },
                                                {
                                                    type: 'Numeric',
                                                    fields: [
                                                        'y'
                                                    ],
                                                    title: 'Numeric Axis',
                                                    position: 'left'
                                                }
                                            ],
                                            series: [
                                                {
                                                    type: 'column',
                                                    label: {
                                                        display: 'insideEnd',
                                                        field: 'y',
                                                        color: '#333',
                                                        'text-anchor': 'middle'
                                                    },
                                                    xField: 'x',
                                                    yField: 'y'
                                                }
                                            ],
                                            legend: {

                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    flex: 1,
                                    layout: 'fit',
                                    title: 'Idle Connections',
                                    dockedItems: [
                                        {
                                            xtype: 'chart',
                                            dock: 'top',
                                            height: 250,
                                            width: 400,
                                            animate: true,
                                            insetPadding: 20,
                                            store: 'TempoStore',
                                            axes: [
                                                {
                                                    type: 'Category',
                                                    fields: [
                                                        'x'
                                                    ],
                                                    title: 'Category Axis',
                                                    position: 'bottom'
                                                },
                                                {
                                                    type: 'Numeric',
                                                    fields: [
                                                        'y'
                                                    ],
                                                    title: 'Numeric Axis',
                                                    position: 'left'
                                                }
                                            ],
                                            series: [
                                                {
                                                    type: 'column',
                                                    label: {
                                                        display: 'insideEnd',
                                                        field: 'y',
                                                        color: '#333',
                                                        'text-anchor': 'middle'
                                                    },
                                                    xField: 'x',
                                                    yField: 'y'
                                                }
                                            ],
                                            legend: {

                                            }
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            autoScroll: true,
                            title: 'Web',
                            items: [
                                {
                                    xtype: 'panel',
                                    layout: 'fit',
                                    title: 'Request statistics',
                                    dockedItems: [
                                        {
                                            xtype: 'chart',
                                            dock: 'top',
                                            height: 250,
                                            width: 400,
                                            animate: true,
                                            insetPadding: 20,
                                            store: 'TempoStore',
                                            axes: [
                                                {
                                                    type: 'Category',
                                                    fields: [
                                                        'x'
                                                    ],
                                                    title: 'Category Axis',
                                                    position: 'bottom'
                                                },
                                                {
                                                    type: 'Numeric',
                                                    fields: [
                                                        'y'
                                                    ],
                                                    title: 'Numeric Axis',
                                                    position: 'left'
                                                }
                                            ],
                                            series: [
                                                {
                                                    type: 'column',
                                                    label: {
                                                        display: 'insideEnd',
                                                        field: 'y',
                                                        color: '#333',
                                                        'text-anchor': 'middle'
                                                    },
                                                    xField: 'x',
                                                    yField: 'y'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            autoScroll: true,
                            title: 'Web application',
                            dockedItems: [
                                {
                                    xtype: 'container',
                                    dock: 'top',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            margin: '5 5 5 5',
                                            layout: 'fit',
                                            title: 'Active Sessions',
                                            dockedItems: [
                                                {
                                                    xtype: 'chart',
                                                    dock: 'top',
                                                    height: 250,
                                                    width: 400,
                                                    animate: true,
                                                    insetPadding: 20,
                                                    store: 'TempoStore',
                                                    axes: [
                                                        {
                                                            type: 'Category',
                                                            fields: [
                                                                'x'
                                                            ],
                                                            title: 'Category Axis',
                                                            position: 'bottom'
                                                        },
                                                        {
                                                            type: 'Numeric',
                                                            fields: [
                                                                'y'
                                                            ],
                                                            title: 'Numeric Axis',
                                                            position: 'left'
                                                        }
                                                    ],
                                                    series: [
                                                        {
                                                            type: 'line',
                                                            xField: 'x',
                                                            yField: 'y',
                                                            smooth: 3
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ],
                            items: [
                                {
                                    xtype: 'container',
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            margin: '5 5 5 5',
                                            title: 'Application Summary',
                                            forceFit: true,
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'Context'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'number',
                                                    text: 'Status'
                                                },
                                                {
                                                    xtype: 'datecolumn',
                                                    dataIndex: 'date',
                                                    text: 'Processing Times(s)'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Successful Requests'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Failed Requests'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Avg. Response Time(ms)'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Avg. Requests/min'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Avg Bytes/secs'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Active Sessions'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Expired Sessions'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Rejected Sessions'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Health'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ],
                    listeners: {
                        tabchange: {
                            fn: me.onDetailTomcatMonitoringTabTabChange,
                            scope: me
                        }
                    }
                }
            ]
        });

        me.callParent(arguments);
    },

    onDetailTomcatMonitoringTabTabChange: function(tabPanel, newCard, oldCard, eOpts) {
        var activeTab = tabPanel.getActiveTab();
        var activeTabIndex =tabPanel.items.findIndex('id', activeTab.id);
        var tomcatId = 1;
        var interVal = setInterval(function(){
                webapp.app.getController("TomcatController").loadDataBusyThreadChart(tomcatId);
         }, 5000);

        if(activeTabIndex == 2) {//thread tab
            webapp.app.getController("TomcatController").loadDataBusyThreadChart(tomcatId);

        }
        else {

            clearInterval(interVal);

        }
    }

});