/*
 * File: app/view/DomainContainer.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('webapp.view.DomainContainer', {
    extend: 'Ext.container.Container',
    alias: 'widget.domaincontainer',

    requires: [
        'Ext.form.field.Display',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.toolbar.Separator',
        'Ext.form.field.ComboBox',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.toolbar.Paging',
        'Ext.grid.plugin.RowEditing'
    ],

    itemId: 'mycontainer37',
    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    flex: 1.5,
                    region: 'north',
                    height: 150,
                    layout: 'column',
                    title: 'Overview',
                    items: [
                        {
                            xtype: 'displayfield',
                            id: 'domainNameField',
                            width: 164,
                            fieldLabel: 'Name',
                            labelWidth: 50,
                            name: 'DomainNameField',
                            value: 'Domain 1'
                        },
                        {
                            xtype: 'displayfield',
                            id: 'tomcatInstancesField',
                            width: 150,
                            fieldLabel: 'Tomcat instances:',
                            labelWidth: 70,
                            name: 'TomcatInstanceQuantityField',
                            value: '4'
                        },
                        {
                            xtype: 'displayfield',
                            id: 'domainTypeField',
                            width: 249,
                            fieldLabel: 'Type',
                            labelWidth: 50,
                            name: 'DomainTypeField',
                            value: 'Clustering'
                        },
                        {
                            xtype: 'displayfield',
                            id: 'datagridServerGroupField',
                            style: '{text-align:right;font-weight:bold;}',
                            width: 218,
                            fieldLabel: 'Data grid server group:',
                            name: 'DataGridServerGroupField',
                            value: 'Group 1'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'panel',
                            dock: 'right',
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'mybutton68',
                                    margin: '50 5 0 0',
                                    text: 'Edit'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'tabpanel',
                    flex: 8,
                    region: 'center',
                    split: true,
                    id: 'domainTabs',
                    itemId: 'domainTabs',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            id: 'domainTomcatTab',
                            itemId: 'domainTomcatTab',
                            layout: 'fit',
                            title: 'Tomcat instances',
                            tabConfig: {
                                xtype: 'tab',
                                id: 'tomcatTabConfig'
                            },
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            id: 'btnNewTomcat',
                                            itemId: 'btnNewTomcat',
                                            text: 'New'
                                        },
                                        {
                                            xtype: 'tbseparator'
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Filtering'
                                        },
                                        {
                                            xtype: 'tbseparator'
                                        },
                                        {
                                            xtype: 'combobox',
                                            fieldLabel: 'Version'
                                        }
                                    ]
                                }
                            ],
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    id: 'associatedTomcatGridView',
                                    title: '',
                                    forceFit: true,
                                    store: 'TomcatInstanceListStore',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'name',
                                            text: 'Name'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'ipaddress',
                                            text: 'IP Address'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'hostName',
                                            text: 'Host Name'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'statusString',
                                            text: 'Status'
                                        }
                                    ],
                                    viewConfig: {
                                        id: 'associatedTomcatListView'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            layout: 'fit',
                            title: 'Applications',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    id: 'associatedApplicationListView',
                                    title: '',
                                    forceFit: true,
                                    store: 'ApplicationStore',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'contextPath',
                                            text: 'Context path'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'displayName',
                                            text: 'Name'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'warPath',
                                            text: '*.war path'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'version',
                                            text: 'Version'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'state',
                                            text: 'State'
                                        }
                                    ],
                                    viewConfig: {
                                        listeners: {
                                            itemclick: {
                                                fn: me.onViewItemClick,
                                                scope: me
                                            }
                                        }
                                    },
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    id: 'btnApplicationDeploy',
                                                    text: 'Deploy'
                                                },
                                                {
                                                    xtype: 'button',
                                                    disabled: true,
                                                    id: 'btnApplicationStart',
                                                    text: 'Start'
                                                },
                                                {
                                                    xtype: 'button',
                                                    disabled: true,
                                                    id: 'btnApplicationRestart',
                                                    text: 'Restart'
                                                },
                                                {
                                                    xtype: 'button',
                                                    disabled: true,
                                                    id: 'btnApplicationStop',
                                                    text: 'Stop'
                                                },
                                                {
                                                    xtype: 'button',
                                                    disabled: true,
                                                    id: 'btnApplicationUndeploy',
                                                    text: 'Undeploy'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            layout: 'fit',
                            title: 'Sessions',
                            dockedItems: [
                                {
                                    xtype: 'gridpanel',
                                    dock: 'top',
                                    id: 'domainSessionGridView',
                                    title: '',
                                    forceFit: true,
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'string',
                                            text: 'Key'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            dataIndex: 'number',
                                            text: 'Value'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            dataIndex: 'date',
                                            text: 'Location'
                                        }
                                    ],
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    fieldLabel: 'Filtering'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'pagingtoolbar',
                                    dock: 'top',
                                    width: 360,
                                    displayInfo: true
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            id: 'clusteringConfigTab',
                            itemId: 'clusteringConfigTab',
                            layout: 'fit',
                            title: 'Clustering configuration',
                            tabConfig: {
                                xtype: 'tab',
                                id: 'clusteringConfigHeader'
                            },
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            itemId: 'btnNewClutersingConfiguration',
                                            text: 'New'
                                        },
                                        {
                                            xtype: 'tbseparator'
                                        },
                                        {
                                            xtype: 'textfield',
                                            itemId: 'mytextfield3',
                                            fieldLabel: 'Filtering'
                                        },
                                        {
                                            xtype: 'tbseparator'
                                        },
                                        {
                                            xtype: 'combobox',
                                            fieldLabel: 'Version'
                                        },
                                        {
                                            xtype: 'button',
                                            text: 'Set active'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'bottom',
                                    height: 42,
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            fieldLabel: 'Compare to'
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'btnComparingClusteringConfiguration',
                                            text: 'Compare'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridpanel',
                                    dock: 'top',
                                    id: 'clusteringConfigurationGridView',
                                    title: '',
                                    forceFit: true,
                                    store: 'ClusteringConfigurationStore',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'name',
                                            text: 'Name'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'value',
                                            text: 'Value'
                                        }
                                    ],
                                    listeners: {
                                        itemcontextmenu: {
                                            fn: me.onClusteringConfigurationGridViewItemContextMenu,
                                            scope: me
                                        }
                                    },
                                    plugins: [
                                        Ext.create('Ext.grid.plugin.RowEditing', {

                                        })
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onViewItemClick: function(dataview, record, item, index, e, eOpts) {

        var status = record.get("state");
        if(status === 1) { //started
            Ext.getCmp("btnApplicationStart").disable();
            Ext.getCmp("btnApplicationStop").enable();
            Ext.getCmp("btnApplicationRestart").enable();
            Ext.getCmp("btnApplicationUndeploy").disable();
        } else if(status  === 2) { //stopped
            Ext.getCmp("btnApplicationStart").enable();
            Ext.getCmp("btnApplicationStop").disable();
            Ext.getCmp("btnApplicationRestart").disable();
            Ext.getCmp("btnApplicationUndeploy").enable();
        }
    },

    onClusteringConfigurationGridViewItemContextMenu: function(dataview, record, item, index, e, eOpts) {
        var mnuContext = Ext.create("Ext.menu.Menu",{

                    items: [{
                        id: 'edit-clustering-config',
                        text: 'Edit'
                    },
                    {
                        id: 'delete-clustering-config',
                        text: 'Delete'
                    }
                           ],
                    listeners: {

                        click: function( _menu, _item, _e, _eOpts ) {
                           switch (_item.id) {
                                case 'edit-clustering-config':
                                    webapp.app.getController("CluteringConfigurationController").showClusteringConfigurationWindow("edit", record.get("id"), GlobalData.lastSelectedMenuId);
                                    break;
                                case 'delete-clustering-config':
                                    webapp.app.getController("CluteringConfigurationController").deleteConfig(record.get("id"));
                                    break;
                                default:
                                    break;
                           }
                        },
                        hide:function(menu){
                            menu.destroy();
                        }
                    },
                    defaults: {
                       clickHideDelay: 1
                    }
                });

                mnuContext.showAt(e.getXY());
                e.stopEvent();
    }

});