/*
 * File: app/view/MonitoringMachineContainer.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('webapp.view.MonitoringMachineContainer', {
    extend: 'Ext.container.Container',
    alias: 'widget.monitoringmachinecontainer',

    requires: [
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Bar',
        'Ext.chart.Legend',
        'Ext.chart.series.Line'
    ],

    layout: {
        align: 'stretch',
        type: 'vbox'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    flex: 9.5,
                    id: 'tabPanel',
                    itemId: 'tabPanel',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            title: 'Availability',
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    flex: 1,
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            text: 'Availability Hisotry in '
                                        },
                                        {
                                            xtype: 'button',
                                            text: 'Last 24 hours',
                                            menu: {
                                                xtype: 'menu',
                                                items: [
                                                    {
                                                        xtype: 'menuitem',
                                                        text: 'Last 30 days'
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 9,
                                    dock: 'top',
                                    layout: {
                                        type: 'fit'
                                    },
                                    items: [
                                        {
                                            xtype: 'chart',
                                            height: 250,
                                            width: 400,
                                            animate: true,
                                            insetPadding: 20,
                                            store: 'TempoStore',
                                            axes: [
                                                {
                                                    type: 'Category',
                                                    fields: [
                                                        'x'
                                                    ],
                                                    position: 'left',
                                                    title: ''
                                                },
                                                {
                                                    type: 'Numeric',
                                                    fields: [
                                                        'y1',
                                                        'y2',
                                                        'y3'
                                                    ],
                                                    position: 'bottom',
                                                    title: 'Numeric Axis'
                                                }
                                            ],
                                            series: [
                                                {
                                                    type: 'bar',
                                                    axis: 'bottom',
                                                    xField: 'x',
                                                    yField: [
                                                        'y1',
                                                        'y2',
                                                        'y3'
                                                    ],
                                                    stacked: true
                                                }
                                            ],
                                            legend: {

                                            }
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            autoScroll: true,
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            title: 'Performance',
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    flex: 0.5,
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            text: 'Tracking in '
                                        },
                                        {
                                            xtype: 'button',
                                            text: 'Last 24 hours',
                                            menu: {
                                                xtype: 'menu',
                                                items: [
                                                    {
                                                        xtype: 'menuitem',
                                                        text: 'Last 30 days'
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 3,
                                    dock: 'top',
                                    layout: {
                                        align: 'stretch',
                                        type: 'hbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            margin: '5 5 5 5',
                                            width: 1226,
                                            layout: {
                                                type: 'fit'
                                            },
                                            title: 'Physical Memory Utilization',
                                            titleAlign: 'center',
                                            dockedItems: [
                                                {
                                                    xtype: 'chart',
                                                    dock: 'top',
                                                    height: 275,
                                                    width: 400,
                                                    animate: true,
                                                    insetPadding: 20,
                                                    store: 'TempoStore',
                                                    axes: [
                                                        {
                                                            type: 'Category',
                                                            fields: [
                                                                'x'
                                                            ],
                                                            title: 'Category Axis',
                                                            position: 'bottom'
                                                        },
                                                        {
                                                            type: 'Numeric',
                                                            fields: [
                                                                'y'
                                                            ],
                                                            title: 'Numeric Axis',
                                                            position: 'left'
                                                        }
                                                    ],
                                                    series: [
                                                        {
                                                            type: 'line',
                                                            axis: 'left',
                                                            xField: 'x',
                                                            yField: 'y',
                                                            smooth: 3
                                                        },
                                                        {
                                                            type: 'line',
                                                            axis: 'left',
                                                            xField: 'x',
                                                            yField: 'y',
                                                            smooth: 3
                                                        }
                                                    ],
                                                    legend: {

                                                    }
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            margin: '5 5 5 5',
                                            width: 1226,
                                            layout: {
                                                type: 'fit'
                                            },
                                            title: 'CPU Utlization',
                                            titleAlign: 'center',
                                            dockedItems: [
                                                {
                                                    xtype: 'chart',
                                                    dock: 'top',
                                                    height: 271,
                                                    width: 400,
                                                    animate: true,
                                                    insetPadding: 20,
                                                    store: 'TempoStore',
                                                    axes: [
                                                        {
                                                            type: 'Category',
                                                            fields: [
                                                                'x'
                                                            ],
                                                            title: 'Category Axis',
                                                            position: 'bottom'
                                                        },
                                                        {
                                                            type: 'Numeric',
                                                            fields: [
                                                                'y'
                                                            ],
                                                            title: 'Numeric Axis',
                                                            position: 'left'
                                                        }
                                                    ],
                                                    series: [
                                                        {
                                                            type: 'line',
                                                            xField: 'x',
                                                            yField: 'y',
                                                            smooth: 3
                                                        },
                                                        {
                                                            type: 'line',
                                                            axis: 'left',
                                                            xField: 'x',
                                                            yField: 'y',
                                                            smooth: 3
                                                        }
                                                    ],
                                                    legend: {

                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 3,
                                    dock: 'top',
                                    layout: {
                                        align: 'stretch',
                                        type: 'hbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            margin: '5 5 5 5',
                                            width: 1226,
                                            layout: {
                                                type: 'fit'
                                            },
                                            title: 'Physical Memory Utilization',
                                            titleAlign: 'center',
                                            dockedItems: [
                                                {
                                                    xtype: 'chart',
                                                    dock: 'top',
                                                    height: 314,
                                                    width: 400,
                                                    animate: true,
                                                    insetPadding: 20,
                                                    store: 'TempoStore',
                                                    axes: [
                                                        {
                                                            type: 'Category',
                                                            fields: [
                                                                'x'
                                                            ],
                                                            title: 'Category Axis',
                                                            position: 'bottom'
                                                        },
                                                        {
                                                            type: 'Numeric',
                                                            fields: [
                                                                'y'
                                                            ],
                                                            title: 'Numeric Axis',
                                                            position: 'left'
                                                        }
                                                    ],
                                                    series: [
                                                        {
                                                            type: 'line',
                                                            xField: 'x',
                                                            yField: 'y',
                                                            smooth: 3
                                                        },
                                                        {
                                                            type: 'line',
                                                            axis: 'left',
                                                            xField: 'x',
                                                            yField: 'y',
                                                            smooth: 3
                                                        }
                                                    ],
                                                    legend: {

                                                    }
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            margin: '5 5 5 5',
                                            width: 1226,
                                            layout: {
                                                type: 'fit'
                                            },
                                            title: 'CPU Utlization',
                                            titleAlign: 'center',
                                            dockedItems: [
                                                {
                                                    xtype: 'chart',
                                                    dock: 'top',
                                                    height: 311,
                                                    width: 400,
                                                    animate: true,
                                                    insetPadding: 20,
                                                    store: 'TempoStore',
                                                    axes: [
                                                        {
                                                            type: 'Category',
                                                            fields: [
                                                                'x'
                                                            ],
                                                            title: 'Category Axis',
                                                            position: 'bottom'
                                                        },
                                                        {
                                                            type: 'Numeric',
                                                            fields: [
                                                                'y'
                                                            ],
                                                            title: 'Numeric Axis',
                                                            position: 'left'
                                                        }
                                                    ],
                                                    series: [
                                                        {
                                                            type: 'line',
                                                            xField: 'x',
                                                            yField: 'y',
                                                            smooth: 3
                                                        },
                                                        {
                                                            type: 'line',
                                                            axis: 'left',
                                                            xField: 'x',
                                                            yField: 'y',
                                                            smooth: 3
                                                        }
                                                    ],
                                                    legend: {

                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    flex: 3.5,
                                    dock: 'top',
                                    width: 400,
                                    layout: {
                                        align: 'stretch',
                                        type: 'hbox'
                                    },
                                    collapsible: true,
                                    manageHeight: false,
                                    title: 'Health history',
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'label',
                                                    text: 'Filtering in'
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Last 24 hours',
                                                    menu: {
                                                        xtype: 'menu',
                                                        items: [
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'Lst 30 days'
                                                            }
                                                        ]
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});