/*
 * File: app/view/ServerManagementContainer.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('webapp.view.ServerManagementContainer', {
    extend: 'Ext.container.Container',
    alias: 'widget.servermanagementcontainer',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.column.Action',
        'Ext.grid.View',
        'Ext.toolbar.Paging',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Display',
        'Ext.form.field.Hidden',
        'Ext.form.field.Checkbox'
    ],

    itemId: 'mycontainer31',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    flex: 9,
                    height: 597,
                    items: [
                        {
                            xtype: 'panel',
                            autoScroll: true,
                            manageHeight: false,
                            title: 'Tomcat servers',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    flex: 1,
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            text: 'New Server'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    dock: 'top',
                                    id: 'tomcatServerGrid',
                                    margin: '',
                                    title: '',
                                    forceFit: true,
                                    store: 'ServerStore',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'name',
                                            text: 'Server name'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'osName',
                                            text: 'Operating System'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'sshipaddr',
                                            text: 'IP Address'
                                        },
                                        {
                                            xtype: 'actioncolumn',
                                            dataIndex: 'tomcatInstanceNo',
                                            text: 'Action'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    flex: 1,
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'pagingtoolbar',
                                            width: 1125,
                                            displayInfo: true,
                                            store: 'ServerStore'
                                        }
                                    ]
                                }
                            ],
                            items: [
                                {
                                    xtype: 'tabpanel',
                                    flex: 7,
                                    id: 'detailTomcatServerTab',
                                    manageHeight: false,
                                    activeTab: 1,
                                    items: [
                                        {
                                            xtype: 'panel',
                                            autoScroll: true,
                                            title: 'Information',
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    margin: '10 10 10 10'
                                                },
                                                {
                                                    xtype: 'form',
                                                    height: 228,
                                                    bodyPadding: 10,
                                                    title: '',
                                                    items: [
                                                        {
                                                            xtype: 'textfield',
                                                            anchor: '100%',
                                                            id: 'serverNameTextField',
                                                            fieldLabel: 'Server name'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            anchor: '100%',
                                                            id: 'serverHostNameTextField',
                                                            fieldLabel: 'Host name',
                                                            readOnly: true
                                                        },
                                                        {
                                                            xtype: 'combobox',
                                                            anchor: '100%',
                                                            id: 'serverSSHIPAddressCombobox',
                                                            fieldLabel: 'SSH IPAddress',
                                                            readOnly: true,
                                                            store: 'TempoStore'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            anchor: '100%',
                                                            id: 'serverSSHPortTextField',
                                                            fieldLabel: 'SSH Port',
                                                            readOnly: true
                                                        },
                                                        {
                                                            xtype: 'displayfield',
                                                            anchor: '100%',
                                                            id: 'serverOSNameDisplayField',
                                                            fieldLabel: 'OS Name'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            text: 'Edit'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            text: 'Save'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            text: 'Cancel'
                                                        },
                                                        {
                                                            xtype: 'hiddenfield',
                                                            id: 'serverIDHiddenField_',
                                                            fieldLabel: 'Label'
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            autoScroll: true,
                                            title: 'SSH Account',
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    margin: '10 10 10 10',
                                                    items: [
                                                        {
                                                            xtype: 'form',
                                                            id: 'sshFormPanel',
                                                            bodyPadding: 10,
                                                            title: '',
                                                            items: [
                                                                {
                                                                    xtype: 'textfield',
                                                                    id: 'tomcatSSHIPAddressTextField',
                                                                    fieldLabel: 'IP Address:',
                                                                    readOnly: true,
                                                                    allowBlank: false
                                                                },
                                                                {
                                                                    xtype: 'textfield',
                                                                    id: 'tomcatSSHPortTextField',
                                                                    fieldLabel: 'Port',
                                                                    readOnly: true,
                                                                    allowBlank: false
                                                                },
                                                                {
                                                                    xtype: 'textfield',
                                                                    id: 'tomcatSSHUserIDTextField',
                                                                    fieldLabel: 'User ID',
                                                                    readOnly: true,
                                                                    allowBlank: false
                                                                },
                                                                {
                                                                    xtype: 'container',
                                                                    layout: {
                                                                        type: 'hbox',
                                                                        align: 'stretch'
                                                                    },
                                                                    items: [
                                                                        {
                                                                            xtype: 'textfield',
                                                                            id: 'tomcatSSHPasswordTextField',
                                                                            width: 255,
                                                                            fieldLabel: 'Password',
                                                                            inputType: 'password',
                                                                            readOnly: true,
                                                                            allowBlank: false
                                                                        },
                                                                        {
                                                                            xtype: 'checkboxfield',
                                                                            itemId: 'showPasswordCheckbox',
                                                                            margin: '0 0 0 10',
                                                                            fieldLabel: '',
                                                                            boxLabel: 'Show password'
                                                                        },
                                                                        {
                                                                            xtype: 'hiddenfield',
                                                                            flex: 1,
                                                                            id: 'serverIDHiddenField',
                                                                            fieldLabel: 'Label'
                                                                        }
                                                                    ]
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    id: 'tbnServerSSHTestConnection',
                                                                    text: 'Test'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    itemId: 'btnServerSSHEdit',
                                                                    margin: '10 10 10 10',
                                                                    text: 'Edit'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    disabled: true,
                                                                    hidden: true,
                                                                    id: 'btnServerSSHSave',
                                                                    itemId: '',
                                                                    margin: '10 10 10 10',
                                                                    text: 'Save'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    id: 'btnServerSSHReset',
                                                                    text: 'Reset'
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ],
                                    listeners: {
                                        tabchange: {
                                            fn: me.onDetailTomcatServerTabTabChange,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ],
                    listeners: {
                        tabchange: {
                            fn: me.onTabpanelTabChange,
                            scope: me
                        }
                    }
                }
            ]
        });

        me.callParent(arguments);
    },

    onDetailTomcatServerTabTabChange: function(tabPanel, newCard, oldCard, eOpts) {


        var activeTab = tabPanel.getActiveTab();
        var activeTabIndex = tabPanel.items.findIndex('id', activeTab.id);
        if(activeTabIndex === 2) { //env tab
            try{
                var selectedRecords;
                selectedRecords = Ext.getCmp('tomcatServerGrid').getSelectionModel().getSelection();
                var serverId = selectedRecords[0].get("id");

                //load EV revisions
                webapp.app.getController("ServerManagementController").loadEVRevisions(serverId, function(data){
                        Ext.getCmp("evRevisionComboBox").getStore().loadData(data);
                    });

                webapp.app.getController("ServerManagementController").loadEnvironmentVariables(serverId, function(data){
                    Ext.getCmp("environmentVariablesGridPanel").getStore().loadData(data);
                });
            }catch(e){

                Ext.Msg.show({
                    title: "Message",
                    msg: "Please choose tomcat server",
                    buttons: Ext.Msg.OK,
                    icon: Ext.Msg.WARNING
                });
            }

        }
    },

    onTabpanelTabChange: function() {
        var activeTab = tabPanel.getActiveTab();
        var activeTabIndex = tabPanel.items.findIndex('id', activeTab.id);
        if(activeTabIndex === 0) {//tomcat server tab
            webapp.app.getController("ServerManagementController").loadTomcatServers(function(data){
                Ext.getCmp("tomcatServerGrid").getStore().loadData(data);
            });
        }
        else if(activeTabIndex === 1) {//datagrid server tab
            Ext.getCmp("datagridServerGroupGrid").getStore().reload();
        }

    }

});