/*
 * File: app/view/ServerManagementContainer.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('webapp.view.ServerManagementContainer', {
    extend: 'Ext.container.Container',
    alias: 'widget.servermanagementcontainer',

    requires: [
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.column.Boolean',
        'Ext.grid.View',
        'Ext.toolbar.Paging',
        'Ext.form.field.ComboBox',
        'Ext.toolbar.Separator',
        'Ext.form.FieldSet',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio'
    ],

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    flex: 9,
                    height: 597,
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            autoScroll: true,
                            manageHeight: false,
                            title: 'Tomcat servers',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    flex: 1,
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            text: 'New Server'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    dock: 'top',
                                    title: '',
                                    forceFit: true,
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'string',
                                            text: 'Name'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            dataIndex: 'number',
                                            text: 'Operating System'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            dataIndex: 'date',
                                            text: 'Type'
                                        },
                                        {
                                            xtype: 'booleancolumn',
                                            dataIndex: 'bool',
                                            text: 'IP Address'
                                        },
                                        {
                                            xtype: 'booleancolumn',
                                            dataIndex: 'bool',
                                            text: 'Tomcat Instances'
                                        }
                                    ],
                                    dockedItems: [
                                        {
                                            xtype: 'pagingtoolbar',
                                            dock: 'bottom',
                                            width: 360,
                                            displayInfo: true
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    flex: 1,
                                    dock: 'top'
                                }
                            ],
                            items: [
                                {
                                    xtype: 'tabpanel',
                                    flex: 7,
                                    manageHeight: false,
                                    activeTab: 0,
                                    items: [
                                        {
                                            xtype: 'panel',
                                            autoScroll: true,
                                            title: 'SSH Account',
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    items: [
                                                        {
                                                            xtype: 'textfield',
                                                            fieldLabel: 'IP Address:'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            fieldLabel: 'Port'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            fieldLabel: 'User ID'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            fieldLabel: 'Password',
                                                            inputType: 'password'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            text: 'Test'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            text: 'Edit'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            text: 'Reset'
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            title: 'Environment Variables',
                                            dockedItems: [
                                                {
                                                    xtype: 'toolbar',
                                                    dock: 'top',
                                                    items: [
                                                        {
                                                            xtype: 'combobox',
                                                            fieldLabel: 'Select revision:'
                                                        },
                                                        {
                                                            xtype: 'tbseparator'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            text: 'Active'
                                                        },
                                                        {
                                                            xtype: 'tbseparator'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            text: 'New'
                                                        }
                                                    ]
                                                }
                                            ],
                                            items: [
                                                {
                                                    xtype: 'gridpanel',
                                                    title: '',
                                                    forceFit: true,
                                                    columns: [
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'string',
                                                            text: 'Variable name'
                                                        },
                                                        {
                                                            xtype: 'numbercolumn',
                                                            dataIndex: 'number',
                                                            text: 'Value'
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            layout: 'fit',
                                            manageHeight: false,
                                            title: 'Server.xml',
                                            items: [
                                                {
                                                    xtype: 'tabpanel',
                                                    width: 100,
                                                    activeTab: 0,
                                                    items: [
                                                        {
                                                            xtype: 'panel',
                                                            collapseDirection: 'top',
                                                            title: 'GUI',
                                                            dockedItems: [
                                                                {
                                                                    xtype: 'fieldset',
                                                                    dock: 'top',
                                                                    margin: '10 0 0 0 0',
                                                                    layout: 'column',
                                                                    title: 'GlobalNamingResources',
                                                                    items: [
                                                                        {
                                                                            xtype: 'textfield',
                                                                            width: 414,
                                                                            fieldLabel: 'Auth'
                                                                        },
                                                                        {
                                                                            xtype: 'textfield',
                                                                            margin: '0 20 10 10 ',
                                                                            width: 414,
                                                                            fieldLabel: 'Description',
                                                                            labelWidth: 120
                                                                        }
                                                                    ]
                                                                },
                                                                {
                                                                    xtype: 'fieldset',
                                                                    dock: 'top',
                                                                    layout: 'column',
                                                                    title: 'Executor.Service',
                                                                    items: [
                                                                        {
                                                                            xtype: 'textfield',
                                                                            width: 414,
                                                                            fieldLabel: 'Max Threads'
                                                                        },
                                                                        {
                                                                            xtype: 'textfield',
                                                                            margin: '0 10 10 10',
                                                                            width: 414,
                                                                            fieldLabel: 'Min Spare Threads',
                                                                            labelWidth: 120
                                                                        },
                                                                        {
                                                                            xtype: 'textfield',
                                                                            width: 414,
                                                                            fieldLabel: 'Max Idle Time'
                                                                        }
                                                                    ]
                                                                },
                                                                {
                                                                    xtype: 'fieldset',
                                                                    dock: 'top',
                                                                    height: 151,
                                                                    layout: 'column',
                                                                    title: 'Connector.Service',
                                                                    items: [
                                                                        {
                                                                            xtype: 'textfield',
                                                                            margin: '0 0 10 0',
                                                                            width: 414,
                                                                            fieldLabel: 'Port',
                                                                            labelWidth: 120
                                                                        },
                                                                        {
                                                                            xtype: 'textfield',
                                                                            margin: '0 10 10 10',
                                                                            width: 414,
                                                                            fieldLabel: 'Executor'
                                                                        },
                                                                        {
                                                                            xtype: 'textfield',
                                                                            margin: '0 0 10 0',
                                                                            width: 414,
                                                                            fieldLabel: 'Connection Timeout',
                                                                            labelWidth: 120
                                                                        },
                                                                        {
                                                                            xtype: 'textfield',
                                                                            margin: '0 0 10 10',
                                                                            width: 414,
                                                                            fieldLabel: 'Redirect Port'
                                                                        },
                                                                        {
                                                                            xtype: 'textfield',
                                                                            margin: '',
                                                                            width: 414,
                                                                            fieldLabel: 'URI Encoding',
                                                                            labelWidth: 120
                                                                        },
                                                                        {
                                                                            xtype: 'textfield',
                                                                            margin: '0 0 0 10',
                                                                            width: 414,
                                                                            fieldLabel: 'Max Post Size'
                                                                        },
                                                                        {
                                                                            xtype: 'radiogroup',
                                                                            margin: '10 10 10 0',
                                                                            width: 414,
                                                                            fieldLabel: 'Use Body Encoding For URI',
                                                                            labelWidth: 200,
                                                                            items: [
                                                                                {
                                                                                    xtype: 'radiofield',
                                                                                    boxLabel: 'Yes'
                                                                                },
                                                                                {
                                                                                    xtype: 'radiofield',
                                                                                    boxLabel: 'No'
                                                                                }
                                                                            ]
                                                                        }
                                                                    ]
                                                                },
                                                                {
                                                                    xtype: 'fieldset',
                                                                    dock: 'top',
                                                                    height: 78,
                                                                    layout: 'column',
                                                                    title: 'Host',
                                                                    items: [
                                                                        {
                                                                            xtype: 'textfield',
                                                                            margin: '0 0 10 0',
                                                                            width: 414,
                                                                            fieldLabel: 'AppBase'
                                                                        },
                                                                        {
                                                                            xtype: 'textfield',
                                                                            margin: '0 10 10 10',
                                                                            width: 414,
                                                                            fieldLabel: 'XmlBase'
                                                                        },
                                                                        {
                                                                            xtype: 'radiogroup',
                                                                            margin: '0 10 10 0',
                                                                            width: 414,
                                                                            fieldLabel: 'Use Body Encoding For URI',
                                                                            labelWidth: 200,
                                                                            items: [
                                                                                {
                                                                                    xtype: 'radiofield',
                                                                                    boxLabel: 'Yes'
                                                                                },
                                                                                {
                                                                                    xtype: 'radiofield',
                                                                                    boxLabel: 'No'
                                                                                }
                                                                            ]
                                                                        }
                                                                    ]
                                                                },
                                                                {
                                                                    xtype: 'toolbar',
                                                                    dock: 'top',
                                                                    items: [
                                                                        {
                                                                            xtype: 'button',
                                                                            margin: '0 0 0 400',
                                                                            text: 'Save'
                                                                        },
                                                                        {
                                                                            xtype: 'button',
                                                                            margin: '0 0 0 50',
                                                                            text: 'Reset'
                                                                        }
                                                                    ]
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'panel',
                                                            title: 'XML Editor'
                                                        }
                                                    ]
                                                }
                                            ],
                                            dockedItems: [
                                                {
                                                    xtype: 'toolbar',
                                                    dock: 'top',
                                                    items: [
                                                        {
                                                            xtype: 'combobox',
                                                            fieldLabel: 'Select revision'
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            layout: 'fit',
                                            manageHeight: false,
                                            title: 'Context.xml',
                                            items: [
                                                {
                                                    xtype: 'tabpanel',
                                                    width: 100,
                                                    activeTab: 0,
                                                    items: [
                                                        {
                                                            xtype: 'panel',
                                                            collapseDirection: 'top',
                                                            manageHeight: false,
                                                            title: 'GUI',
                                                            dockedItems: [
                                                                {
                                                                    xtype: 'fieldset',
                                                                    dock: 'top',
                                                                    height: 244,
                                                                    layout: 'column',
                                                                    title: '',
                                                                    items: [
                                                                        {
                                                                            xtype: 'textfield',
                                                                            margin: '10 0 10 0',
                                                                            width: 414,
                                                                            fieldLabel: 'DocBase'
                                                                        },
                                                                        {
                                                                            xtype: 'textfield',
                                                                            margin: '10 0 10 10',
                                                                            width: 414,
                                                                            fieldLabel: 'Path'
                                                                        },
                                                                        {
                                                                            xtype: 'radiogroup',
                                                                            margin: '10 10 10 0',
                                                                            width: 414,
                                                                            fieldLabel: 'Reloadable',
                                                                            items: [
                                                                                {
                                                                                    xtype: 'radiofield',
                                                                                    boxLabel: 'Yes'
                                                                                },
                                                                                {
                                                                                    xtype: 'radiofield',
                                                                                    boxLabel: 'No'
                                                                                }
                                                                            ]
                                                                        },
                                                                        {
                                                                            xtype: 'radiogroup',
                                                                            margin: '10 10 10 0',
                                                                            width: 414,
                                                                            fieldLabel: 'CrossContext',
                                                                            items: [
                                                                                {
                                                                                    xtype: 'radiofield',
                                                                                    boxLabel: 'Yes'
                                                                                },
                                                                                {
                                                                                    xtype: 'radiofield',
                                                                                    boxLabel: 'No'
                                                                                }
                                                                            ]
                                                                        },
                                                                        {
                                                                            xtype: 'radiogroup',
                                                                            margin: '10 10 10 0',
                                                                            width: 414,
                                                                            fieldLabel: 'Privileged',
                                                                            items: [
                                                                                {
                                                                                    xtype: 'radiofield',
                                                                                    boxLabel: 'Yes'
                                                                                },
                                                                                {
                                                                                    xtype: 'radiofield',
                                                                                    boxLabel: 'No'
                                                                                }
                                                                            ]
                                                                        },
                                                                        {
                                                                            xtype: 'radiogroup',
                                                                            margin: '10 10 10 0',
                                                                            width: 414,
                                                                            fieldLabel: 'TldValidation',
                                                                            items: [
                                                                                {
                                                                                    xtype: 'radiofield',
                                                                                    boxLabel: 'Yes'
                                                                                },
                                                                                {
                                                                                    xtype: 'radiofield',
                                                                                    boxLabel: 'No'
                                                                                }
                                                                            ]
                                                                        },
                                                                        {
                                                                            xtype: 'radiogroup',
                                                                            margin: '10 10 10 0',
                                                                            width: 414,
                                                                            fieldLabel: 'UseHttpOnly',
                                                                            items: [
                                                                                {
                                                                                    xtype: 'radiofield',
                                                                                    boxLabel: 'Yes'
                                                                                },
                                                                                {
                                                                                    xtype: 'radiofield',
                                                                                    boxLabel: 'No'
                                                                                }
                                                                            ]
                                                                        },
                                                                        {
                                                                            xtype: 'radiogroup',
                                                                            margin: '10 10 10 0',
                                                                            width: 414,
                                                                            fieldLabel: 'XmlValidation',
                                                                            items: [
                                                                                {
                                                                                    xtype: 'radiofield',
                                                                                    boxLabel: 'Yes'
                                                                                },
                                                                                {
                                                                                    xtype: 'radiofield',
                                                                                    boxLabel: 'No'
                                                                                }
                                                                            ]
                                                                        }
                                                                    ]
                                                                },
                                                                {
                                                                    xtype: 'toolbar',
                                                                    dock: 'top',
                                                                    items: [
                                                                        {
                                                                            xtype: 'button',
                                                                            margin: '0 0 0 400',
                                                                            text: 'Save'
                                                                        },
                                                                        {
                                                                            xtype: 'button',
                                                                            margin: '0 0 0 50',
                                                                            text: 'Reset'
                                                                        }
                                                                    ]
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'panel',
                                                            title: 'XML Editor'
                                                        }
                                                    ]
                                                }
                                            ],
                                            dockedItems: [
                                                {
                                                    xtype: 'toolbar',
                                                    dock: 'top',
                                                    items: [
                                                        {
                                                            xtype: 'combobox',
                                                            fieldLabel: 'Select revision'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            title: 'Datagrid Servers',
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            text: 'New Group'
                                        }
                                    ]
                                }
                            ],
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    title: 'Datagrid Server Group',
                                    forceFit: true,
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'string',
                                            text: 'Name'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            dataIndex: 'number',
                                            text: 'Type'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            dataIndex: 'date',
                                            text: 'Servers'
                                        },
                                        {
                                            xtype: 'booleancolumn',
                                            dataIndex: 'bool',
                                            text: 'Action'
                                        }
                                    ],
                                    dockedItems: [
                                        {
                                            xtype: 'pagingtoolbar',
                                            dock: 'bottom',
                                            width: 360,
                                            displayInfo: true
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Detail'
                                },
                                {
                                    xtype: 'gridpanel',
                                    title: '',
                                    forceFit: true,
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'string',
                                            text: 'Server Name'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            dataIndex: 'number',
                                            text: 'Group'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            dataIndex: 'date',
                                            text: 'IP Address'
                                        },
                                        {
                                            xtype: 'booleancolumn',
                                            dataIndex: 'bool',
                                            text: 'Hostname'
                                        },
                                        {
                                            xtype: 'booleancolumn',
                                            dataIndex: 'bool',
                                            text: 'Sessions'
                                        },
                                        {
                                            xtype: 'booleancolumn',
                                            dataIndex: 'bool',
                                            text: 'Status'
                                        },
                                        {
                                            xtype: 'booleancolumn',
                                            dataIndex: 'bool',
                                            text: 'Actions'
                                        }
                                    ],
                                    dockedItems: [
                                        {
                                            xtype: 'pagingtoolbar',
                                            dock: 'bottom',
                                            width: 360,
                                            displayInfo: true
                                        },
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    text: 'Add'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    fieldLabel: 'Filtering'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});