/*
 * File: app/view/SSHFormPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('webapp.view.SSHFormPanel', {
    extend: 'Ext.form.Panel',

    requires: [
        'Ext.form.field.Text',
        'Ext.container.Container',
        'Ext.form.field.Checkbox',
        'Ext.form.field.Hidden',
        'Ext.button.Button'
    ],

    id: 'sshFormPanel',
    bodyPadding: 10,
    title: '',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    id: 'tomcatSSHIPAddressTextField',
                    fieldLabel: 'IP Address:',
                    readOnly: true,
                    allowBlank: false
                },
                {
                    xtype: 'textfield',
                    id: 'tomcatSSHPortTextField',
                    fieldLabel: 'Port',
                    readOnly: true,
                    allowBlank: false
                },
                {
                    xtype: 'textfield',
                    id: 'tomcatSSHUserIDTextField',
                    fieldLabel: 'User ID',
                    readOnly: true,
                    allowBlank: false
                },
                {
                    xtype: 'container',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            id: 'tomcatSSHPasswordTextField',
                            width: 255,
                            fieldLabel: 'Password',
                            inputType: 'password',
                            readOnly: true,
                            allowBlank: false
                        },
                        {
                            xtype: 'checkboxfield',
                            itemId: 'showPasswordCheckbox',
                            margin: '0 0 0 10',
                            fieldLabel: '',
                            boxLabel: 'Show password'
                        },
                        {
                            xtype: 'hiddenfield',
                            flex: 1,
                            id: 'serverIDHiddenField',
                            fieldLabel: 'Label'
                        }
                    ]
                },
                {
                    xtype: 'button',
                    id: 'tbnServerSSHTestConnection',
                    text: 'Test'
                },
                {
                    xtype: 'button',
                    itemId: 'btnServerSSHEdit',
                    margin: '10 10 10 10',
                    text: 'Edit'
                },
                {
                    xtype: 'button',
                    disabled: true,
                    hidden: true,
                    id: 'btnServerSSHSave',
                    itemId: '',
                    margin: '10 10 10 10',
                    text: 'Save'
                },
                {
                    xtype: 'button',
                    id: 'btnServerSSHReset',
                    text: 'Reset'
                }
            ]
        });

        me.callParent(arguments);
    }

});