/*
 * File: app/view/TomcatInstanceContainer.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('webapp.view.TomcatInstanceContainer', {
    extend: 'Ext.container.Container',
    alias: 'widget.tomcatinstancecontainer',

    requires: [
        'Ext.form.field.Display',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.column.Boolean',
        'Ext.grid.View',
        'Ext.toolbar.Paging'
    ],

    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    flex: 3,
                    region: 'north',
                    height: 389,
                    manageHeight: false,
                    title: 'Overview',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'displayfield',
                            width: 164,
                            fieldLabel: 'Host name:',
                            value: 'Tomcat 1'
                        },
                        {
                            xtype: 'displayfield',
                            width: 249,
                            fieldLabel: 'Status',
                            value: 'Started'
                        },
                        {
                            xtype: 'displayfield',
                            width: 249,
                            fieldLabel: 'IP Address',
                            value: '192.168.0.83'
                        },
                        {
                            xtype: 'displayfield',
                            width: 249,
                            fieldLabel: 'Ports:',
                            value: '{HTTP 1.1: 8080, AJP: 8009, redirect: 8443}'
                        },
                        {
                            xtype: 'displayfield',
                            width: 164,
                            fieldLabel: 'Web server',
                            value: 'Apache Tomcat / 7.0.47'
                        },
                        {
                            xtype: 'displayfield',
                            width: 164,
                            fieldLabel: 'JVM Version',
                            value: '1.7.0_45-b18'
                        },
                        {
                            xtype: 'displayfield',
                            width: 164,
                            fieldLabel: 'OS Name',
                            value: 'Linux'
                        },
                        {
                            xtype: 'displayfield',
                            width: 164,
                            fieldLabel: 'Domain',
                            value: 'Domain 1'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    disabled: true,
                                    text: 'Start'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Stop'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Restart'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    flex: 7,
                    region: 'center',
                    margin: '5 0 0 0 ',
                    title: 'Data sources',
                    forceFit: true,
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Name'
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'number',
                            text: 'JDBC URL'
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'date',
                            text: 'Servers'
                        },
                        {
                            xtype: 'booleancolumn',
                            dataIndex: 'bool',
                            text: 'Min Connection Pool'
                        },
                        {
                            xtype: 'booleancolumn',
                            dataIndex: 'bool',
                            text: 'Max Connection Pool'
                        },
                        {
                            xtype: 'booleancolumn',
                            dataIndex: 'bool',
                            text: 'Timeout'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true
                        },
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'btnLinkNewDatasource',
                                    text: 'Link new Datasource'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});