/*
 * File: app/view/TomcatInstanceContainer.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('webapp.view.TomcatInstanceContainer', {
    extend: 'Ext.container.Container',
    alias: 'widget.tomcatinstancecontainer',

    requires: [
        'Ext.form.field.Display',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.column.Boolean',
        'Ext.grid.View',
        'Ext.toolbar.Paging'
    ],

    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    flex: 3,
                    region: 'north',
                    height: 389,
                    manageHeight: false,
                    title: 'Overview',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'displayfield',
                            id: 'tomcatNameField',
                            width: 150,
                            fieldLabel: 'Name',
                            labelWidth: 50,
                            value: ''
                        },
                        {
                            xtype: 'displayfield',
                            id: 'tomcatStateField',
                            width: 150,
                            fieldLabel: 'Status',
                            labelWidth: 50,
                            value: ''
                        },
                        {
                            xtype: 'displayfield',
                            id: 'tomcatIPAddField',
                            width: 200,
                            fieldLabel: 'IP Address',
                            labelWidth: 80,
                            value: ''
                        },
                        {
                            xtype: 'displayfield',
                            id: 'tomcatPortField',
                            width: 200,
                            fieldLabel: 'Ports:',
                            labelWidth: 50,
                            value: ''
                        },
                        {
                            xtype: 'displayfield',
                            id: 'tomcatWebServerField',
                            width: 200,
                            fieldLabel: 'Web server',
                            value: ''
                        },
                        {
                            xtype: 'displayfield',
                            id: 'tomcatJVMVersionField',
                            width: 164,
                            fieldLabel: 'JVM Version',
                            labelWidth: 80,
                            value: ''
                        },
                        {
                            xtype: 'displayfield',
                            id: 'tomcatOSField',
                            width: 164,
                            fieldLabel: 'OS Name',
                            labelWidth: 80,
                            value: 'Linux'
                        },
                        {
                            xtype: 'displayfield',
                            id: 'tomcatDomainField',
                            width: 164,
                            fieldLabel: 'Domain',
                            value: 'Domain 1'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    disabled: true,
                                    id: 'btnTomcatStart',
                                    text: 'Start'
                                },
                                {
                                    xtype: 'button',
                                    id: 'btnTomcatStop',
                                    itemId: '',
                                    text: 'Stop'
                                },
                                {
                                    xtype: 'button',
                                    id: 'btnTomcatRestart',
                                    text: 'Restart'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'tabpanel',
                    flex: 7,
                    region: 'center',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            title: 'Data sources',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    id: 'tomcatDatasourcesGrid',
                                    margin: '5 0 0 0 ',
                                    title: '',
                                    forceFit: true,
                                    store: 'DatasourceStore',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'name',
                                            text: 'Name'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            dataIndex: 'jdbcUrl',
                                            text: 'JDBC URL'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            dataIndex: 'Id',
                                            text: 'Servers'
                                        },
                                        {
                                            xtype: 'booleancolumn',
                                            dataIndex: 'minConnectionPool',
                                            text: 'Min Connection Pool'
                                        },
                                        {
                                            xtype: 'booleancolumn',
                                            dataIndex: 'maxConnectionPool',
                                            text: 'Max Connection Pool'
                                        },
                                        {
                                            xtype: 'booleancolumn',
                                            dataIndex: 'timeout',
                                            text: 'Timeout'
                                        }
                                    ],
                                    dockedItems: [
                                        {
                                            xtype: 'pagingtoolbar',
                                            dock: 'bottom',
                                            width: 360,
                                            displayInfo: true
                                        },
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    id: 'btnLinkNewDatasource',
                                                    text: 'Link new Datasource'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            title: 'Applications',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    id: 'tomcatApplicationGrid',
                                    title: '',
                                    forceFit: true,
                                    store: 'ApplicationStore',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'contextPath',
                                            text: 'Context Path'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'displayName',
                                            text: 'Name'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'warPath',
                                            text: '*.war path'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'version',
                                            text: 'Version'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'state',
                                            text: 'State'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});