/*
 * File: app/view/UserRoleWindow.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('webapp.view.UserRoleWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.UserRoleWindow',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.form.field.Hidden',
        'Ext.button.Button'
    ],

    height: 124,
    id: 'UserRoleWindow',
    width: 440,
    autoScroll: true,
    layout: 'fit',
    title: 'New User Role',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    height: 260,
                    id: 'userRoleForm',
                    bodyPadding: 10,
                    frameHeader: false,
                    header: false,
                    title: 'My Form',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            id: 'userRoleNameTextField',
                            itemId: 'userRoleNameTextField',
                            width: 388,
                            fieldLabel: 'User Role',
                            name: 'UserRoleNameTextField',
                            allowBlank: false,
                            allowOnlyWhitespace: false,
                            emptyText: '',
                            validateBlank: true
                        },
                        {
                            xtype: 'hiddenfield',
                            fieldLabel: 'Label',
                            name: 'IDHiddenField'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'container',
                            flex: 0.5,
                            dock: 'bottom',
                            height: 38,
                            layout: {
                                type: 'hbox',
                                align: 'middle',
                                defaultMargins: {
                                    top: 0,
                                    right: 10,
                                    bottom: 10,
                                    left: 0
                                },
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    margins: '10 10 10 10',
                                    id: 'btnUserRoleSubmit',
                                    itemId: 'btnUserRoleSubmit',
                                    text: 'Create'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        Ext.MessageBox.confirm('Confirm', '작업을 취소하시겠습니까?', function(btn){

                                            if(btn == "yes"){
                                                button.up("window").close();
                                            }
                                        });
                                    },
                                    text: 'Cancel'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});