/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({
    enabled: true
});


Ext.application({
    models: [
        'SessionKeyData',
        'UserModel',
        'UserRoleModel',
        'DatagridModel',
        'EnvironmentVariableModel',
        'RevisionModel',
        'ServerModel',
        'NetworkInterfaceModel',
        'SSHAccountModel',
        'DatasourceModel',
        'DomainModel',
        'TomcatBusyThreadModel',
        'TomcatInstanceModel',
        'ApplicationModel'
    ],
    stores: [
        'sessionDataStore',
        'UserRoleStore',
        'UserStore',
        'DatasourceStore',
        'DatagridServerStore',
        'EnvironmentVariableStore',
        'RevisionStore',
        'ServerStore',
        'NetworkInterfaceStore',
        'SSHAccountStore',
        'MenuTreeStore',
        'TempoStore',
        'DomainStore',
        'LinkingTomcatDatasourceStore',
        'TomcatBusyThreadStore',
        'TomcatInstanceListStore',
        'ApplicationStore',
        'ClusteringConfigurationStore',
        'DatagridServerGroupStore'
    ],
    views: [
        'meerkatViewport',
        'loginWindow',
        'TomcatInstanceWindow',
        'TomcatInstanceContainer',
        'LinkNewDataSourceWindow',
        'UserWindow',
        'EnvironmentVariableWindow',
        'UserRoleWindow',
        'DomainWindow',
        'MonitoringMachineContainer',
        'MonitoringTomcatInstance',
        'ResourceManagementContainer',
        'ServerManagementContainer',
        'SessionServerGroupContainer',
        'SeverDataGridWindow',
        'UserMntContainer',
        'TomcatForm',
        'TomcatInstanceCreateWizard',
        'TomcatInstallLogWindow',
        'SSHFormPanel',
        'dashboardPanel',
        'DataSourceWindow',
        'DeployWindow',
        'DetailMonitoringMachineContainer',
        'DomainContainer',
        'DomainForm'
    ],
    controllers: [
        'headerController',
        'footerController',
        'dashboardController',
        'globalController',
        'LoginController',
        'MenuController',
        'DomainController',
        'TomcatController',
        'UserController',
        'ApplicationController',
        'CluteringConfigurationController',
        'ServerManagementController',
        'DatagridServerController',
        'TomcatInstWizardController',
        'DatasourceController'
    ],
    name: 'webapp',

    launch: function() {
        Ext.create('webapp.view.meerkatViewport');
    }

});
